### ISSUE TITLE
Is this works on kafka version 0.10.0 ?

### ISSUE THREAD

**Issue by jinho-scenappsm** [hubrick/vertx-kafka-service#9]
Hi
Thank for sharing nice kafka-vertx module.

I already have clustered kafka 0.10.0 installed, dose "vertx-kafka-service" works on kafka 0.10.0 version ?

And, If I make 10 instances of http rest api server embeding "vertx-kafka-service" producer processing, dose "vertx-kafka-service" also deployed with 10 instances ?

**Comment by eemmiirr** [comment]
Hi,

I haven't tested it but i am pretty  sure it won't work with 0.10.0 since they are not binary compatible and the configuration propery names changed. If you like you can make a PR with these changes.

Regarding the number of instances. The producer and consumer are running in their own verticle which means the number of this verticles defines the number of created instance. Usually it's enough to create one producer or consumer per vertx app. In your other verticle you can register your handler or create a KafkaProducerService to communicate the the producer verticle.

**Comment by javadevmtl** [comment]
I could be wrong but the kafka protocol states that they try to keep backward compatibility and I installed the latest confluent platform which is 0.10 and the consumer seems to work. Or am I crazy?

**Comment by arisc097** [comment]
eemmirr, any plans to upgrade this to 0.10?

**Comment by eemmiirr** [comment]
sorry for the long silence. I can try upgrade and will test it. If it works out will upgrade to the latest

**Comment by marcust** [comment]
@jinho-scenappsm: master is now running with 0.10.1.0, I plan an releasing 1.3.0 when all PRs are merged.
